### ISSUE TITLE
界面中有地图，地图全黑

### ISSUE THREAD

**Issue by xiagea** [JustRight815/SwipeBackLayoutTouTiao#1]
滑动时能看到地图，但是不滑动全黑

**Comment by JustRight815** [comment]
什么地图？其他界面有问题吗？是不是主题或者布局背景的问题

**Comment by xiagea** [comment]
> 什么地图？其他界面有问题吗？是不是主题或者布局背景的问题

高德地图，主题要修改什么吗，其他界面没问题，布局也没什么特殊的

**Comment by xiagea** [comment]
> 什么地图？其他界面有问题吗？是不是主题或者布局背景的问题

在你的demo里也加了高德地图，一样黑的

**Comment by JustRight815** [comment]
我没有用地图测试过，周末看下吧

**Comment by xiagea** [comment]
> 我没有用地图测试过，周末看下吧

找到原因了，是调用convertActivityFromTranslucent这个方法导致的，有时间看下哈

**Comment by JustRight815** [comment]
> 找到原因了，是调用convertActivityFromTranslucent这个方法导致的，有时间看下哈

调用这个方法是将透明主题的界面转换为不透明，因为透明的界面打开其他界面无法进入onstop方法，打开界面过多的话会卡顿。如果你的地图界面不再打开其他界面，你可以判断下把这个调用屏蔽掉。或者在其他时机调用这个方法。

**Comment by xiagea** [comment]
> > 找到原因了，是调用convertActivityFromTranslucent这个方法导致的，有时间看下哈
> 
> 调用这个方法是将透明主题的界面转换为不透明，因为透明的界面打开其他界面无法进入onstop方法，打开界面过多的话会卡顿。如果你的地图界面不再打开其他界面，你可以判断下把这个调用屏蔽掉。或者在其他时机调用这个方法。

好的，谢谢啦
