### ISSUE TITLE
希望能优化下内存泄漏

### ISSUE THREAD

**Issue by xiagea** [JustRight815/SwipeBackLayoutTouTiao#3]
集成后，LeakCanary老是弹出内存泄漏的信息，是集成前没有出现的泄漏，基本上每个activity都是一个内存泄漏问题

**Comment by JustRight815** [comment]
周末优化下

**Comment by JustRight815** [comment]
> 集成后，LeakCanary老是弹出内存泄漏的信息，是集成前没有出现的泄漏，基本上每个activity都是一个内存泄漏问题

我用LeakCanary检查demo没有这个问题
